// <auto-generated />
using Houseplants.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Houseplants.Migrations
{
    [DbContext(typeof(HouseplantsContext))]
    partial class HouseplantsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Houseplants.Models.Care", b =>
                {
                    b.Property<int>("CareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LightNeed")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("NutritionNeed")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("WaterNeed")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("CareId");

                    b.ToTable("Care");
                });

            modelBuilder.Entity("Houseplants.Models.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FamilyLatin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("FamilyId");

                    b.HasIndex("FamilyLatin")
                        .IsUnique()
                        .HasDatabaseName("UQ__Family__D64B1C7939073458");

                    b.HasIndex("FamilyName")
                        .IsUnique()
                        .HasDatabaseName("UQ__Family__3B1353D64089D866");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("Houseplants.Models.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Care")
                        .HasColumnType("int");

                    b.Property<int>("Family")
                        .HasColumnType("int");

                    b.Property<string>("Latin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Level")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("PlantId");

                    b.HasIndex("Care");

                    b.HasIndex("Family");

                    b.HasIndex("Latin")
                        .IsUnique()
                        .HasDatabaseName("UQ__Plant__E71B2F54976CE9C8");

                    b.HasIndex("PlantName")
                        .IsUnique()
                        .HasDatabaseName("UQ__Plant__3B758BC2AD04B938");

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("Houseplants.Models.Plant", b =>
                {
                    b.HasOne("Houseplants.Models.Care", "CareNavigation")
                        .WithMany("Plant")
                        .HasForeignKey("Care")
                        .HasConstraintName("FK_Care")
                        .IsRequired();

                    b.HasOne("Houseplants.Models.Family", "FamilyNavigation")
                        .WithMany("Plant")
                        .HasForeignKey("Family")
                        .HasConstraintName("FK_Family")
                        .IsRequired();

                    b.Navigation("CareNavigation");

                    b.Navigation("FamilyNavigation");
                });

            modelBuilder.Entity("Houseplants.Models.Care", b =>
                {
                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Houseplants.Models.Family", b =>
                {
                    b.Navigation("Plant");
                });
#pragma warning restore 612, 618
        }
    }
}
